// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_msg.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbr = global::Google.Protobuf.Reflection;
/// <summary>Holder for reflection information generated from test_msg.proto</summary>
public static partial class TestMsgReflection
{

    #region Descriptor
    /// <summary>File descriptor for test_msg.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
        get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestMsgReflection()
    {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "Cg50ZXN0X21zZy5wcm90byIjCgZUaGVNc2cSDAoEbmFtZRgBIAEoCRILCgNu",
              "dW0YAiABKAViBnByb3RvMw=="));
        descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
            new pbr::FileDescriptor[] { },
            new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::TheMsg), global::TheMsg.Parser, new[]{ "Name", "Num" }, null, null, null)
            }));
    }
    #endregion

}
#region Messages
public sealed partial class TheMsg : pb::IMessage<TheMsg>
{
    private static readonly pb::MessageParser<TheMsg> _parser = new pb::MessageParser<TheMsg>(() => new TheMsg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TheMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::TestMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TheMsg()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TheMsg(TheMsg other) : this()
    {
        name_ = other.name_;
        num_ = other.num_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TheMsg Clone()
    {
        return new TheMsg(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name
    {
        get { return name_; }
        set
        {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num
    {
        get { return num_; }
        set
        {
            num_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other)
    {
        return Equals(other as TheMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TheMsg other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Name != other.Name) return false;
        if (Num != other.Num) return false;
        return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        if (Num != 0) hash ^= Num.GetHashCode();
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output)
    {
        if (Name.Length != 0)
        {
            output.WriteRawTag(10);
            output.WriteString(Name);
        }
        if (Num != 0)
        {
            output.WriteRawTag(16);
            output.WriteInt32(Num);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize()
    {
        int size = 0;
        if (Name.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
        }
        if (Num != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TheMsg other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Name.Length != 0)
        {
            Name = other.Name;
        }
        if (other.Num != 0)
        {
            Num = other.Num;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    input.SkipLastField();
                    break;
                case 10:
                    {
                        Name = input.ReadString();
                        break;
                    }
                case 16:
                    {
                        Num = input.ReadInt32();
                        break;
                    }
            }
        }
    }

}

#endregion


#endregion Designer generated code
